[package]
name = "directionlib"
version = "0.1.3"
edition = "2024"
authors = ["vlk"]
description = "A simple direction/axis library providing useful enums, traits and methods"
license = "LGPL-3.0-only"


[dependencies]
arbitrary = { version = "1", default-features = false, optional = true }
bevy-inspector-egui = { version = "0.36", optional = true, default-features = false }
bevy_ecs = { version = "0.18", default-features = false, optional = true }
bevy_math = { version = "0.18.0", default-features = false, optional = true }
bevy_reflect = { version = "0.18", default-features = false, optional = true }
bevy_transform = { version = "0.18", default-features = false, optional = true }
bitflags = { version = "2", default-features = false }
bytemuck = { version = "1", default-features = false, optional = true }
bytemuck_derive = { version = "1", default-features = false, optional = true }
defmt = { version = "1", default-features = false, optional = true }
glam = { version = "0.30", optional = true, default-features = false }
mint = { version = "0.5", default-features = false, optional = true }
nalgebra = { version = "0.34", default-features = false, optional = true }
num-traits = { version = "0.2", default-features = false, optional = true }
serde = { version = "1", default-features = false, optional = true }
serde_derive = { version = "1", default-features = false, optional = true }

[features]
default = []
# default = [
#     "serde",
#     "defmt",
#     "bevy_reflect",
#     "bevy_ecs",
#     "num-traits",
#     "bytemuck",
#     "arbitrary",
#     "glam",
#     "mint",
#     "nalgebra",
#     "glam_std",
#     "bevy-inspector-egui",
#     "bevy_transform",
# ]

# Derive serde traits for all supported structures
serde = ["dep:serde", "dep:serde_derive", "bitflags/serde"]
# Derive defmt formatting
defmt = ["dep:defmt"]
# Derive reflection support
bevy_reflect = ["dep:bevy_reflect"]
# Derive bevy Component traits
bevy_ecs = ["dep:bevy_ecs"]
# Implement helpful number casting
num-traits = ["dep:num-traits"]
# Implement bytemuck traits for supported types
bytemuck = ["dep:bytemuck", "dep:bytemuck_derive", "bitflags/bytemuck"]
# Add arbitrary crate support
arbitrary = ["dep:arbitrary"]
# Implement traits for the `glam` crate types
glam = ["dep:glam"]
# Implement traits for the `mint` crate types, this is the most portable math library
mint = ["dep:mint"]
# (Attempt to) implement traits for the `nalgebra` crate types. Somewhat limited due to lack of specialization.
nalgebra = ["dep:nalgebra"]
# Enable glam-std. Enable this feature to get rustdoc builds to work. Disable if
# building for a no-std crate and you can add glam with whatever backend you choose.
glam_std = ["glam", "glam/std"]
bevy-inspector-egui = ["dep:bevy-inspector-egui"]
bevy_transform = ["dep:bevy_transform", "dep:bevy_math", "glam"]

[dev-dependencies]
# TODO: Only enable glam here if it is also enabled above
glam = { version = "0.30", default-features = false, features = ["std"] }
